spring:
  main:
    banner-mode: off
  application:
    name: ivoy-service
  data:
    mongodb:
      uri: MONGO_URI_HERE
      auto-index-creation: false
      codec:
        max-in-memory-size: 100MB

springdoc:
  api-docs:
    groups:
      enabled: true