spring:
  main:
    banner-mode: off
  application:
    name: ivoy-service
  data:
    mongodb:
      uri: "mongodb+srv://andreshincapier:andreshincapier@cluster0.r2ikq.mongodb.net/dna_analysis?retryWrites=true&w=majority"
      auto-index-creation: false
      codec:
        max-in-memory-size: 100MB

springdoc:
  api-docs:
    groups:
      enabled: true